### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by cleveranu** [ssitvit/Code-Canvas#10]

**Comment by Nishannaik** [comment]
Can I Work on this issue. Please assign it to me

**Comment by Nishannaik** [comment]
Thank u @cleveranu

**Comment by Nishannaik** [comment]
Hey @cleveranu can you give me a guidance what exactly have to do ? In this project as I am beginner.

**Comment by cleveranu** [comment]
Try making a simple music player using HTML,CSS and JS.

**Comment by Nishannaik** [comment]
Hey thanks for your reply @cleveranu I was eagerly waiting for your reply.

**Comment by Nishannaik** [comment]
@vk20july I m working on this issue currently due to my exams till 17 june I was not able to do further i m rready so go with another
