### ISSUE TITLE
[GSSoC'23]New Project - Haunted House

### ISSUE THREAD

**Issue by prrockzed** [ssitvit/Code-Canvas#100]
Category: Fun
An original and fun project, made using Three.js library, with interactive user experience and dynamic movements of ghostly characters. User will be able to move through the whole environment with their mouse as in 3D. Addition of graves and doors and windows will make the project look real.

**Comment by Shreyaar12** [comment]
Sure @prrockzed I will assign this issue to you please complete it within 10 days

**Comment by prrockzed** [comment]
Thanks @Shreyaar12. Will try to complete it within 10 days.

**Comment by prrockzed** [comment]
I have created a pull request. @Dharmesh177 Please review it.
