### ISSUE TITLE
[GSSoC'23] Add project : Weather app

### ISSUE THREAD

**Issue by Abhinavcode13** [ssitvit/Code-Canvas#102]
The weather app front-end project aims to create a user-friendly and visually appealing application that provides accurate and up-to-date weather information to users. The app will allow users to enter their desired location or use their device's GPS functionality to automatically detect their current location. The front-end design will focus on providing an intuitive and responsive user interface that can be accessed from various devices, including desktops, tablets, and smartphones.

Features:

Weather Display
Location-based Forecast
Responsive Design
Visual Enhancements

Technology Stack:

HTML/CSS: To structure and style the user interface.
JavaScript: To handle user interactions, retrieve weather data from APIs, and dynamically update the interface.

Conclusion:
The weather app front-end project aims to deliver a visually appealing, user-friendly, and responsive application that provides accurate weather information to users. By incorporating key features like location-based forecasts, search functionality, and weather alerts, the app will empower users to stay informed about current and upcoming weather conditions.

**Comment by Abhinavcode13** [comment]
Please assign me this issue under gssoc 23 @Shreyaar12 @Dharmesh177

**Comment by Abhinavcode13** [comment]
Waiting for your reply to start the project asap @Shreyaar12 @Dharmesh177 !!!

**Comment by artimanputra** [comment]
> Please assign me this issue under gssoc 23 @Shreyaar12 @Dharmesh177

assigned to @Abhinavcode13 
Complete this within 1 week and
Include a screenshot or deploy link to assess your project and thereafter include your project in the main code with the following contributing.md guidelines.
