### ISSUE TITLE
Clone of Wikipedia

### ISSUE THREAD

**Issue by cleveranu** [ssitvit/Code-Canvas#11]
Wikipedia features a straightforward structure that is always the same, along with a wealth of material that is simply divided into many parts.

**Comment by nikim178** [comment]
@cleveranu I'm interested in working on it. May I have permission to tackle this issue?

**Comment by nikim178** [comment]
thank you !!@cleveranu

**Comment by nikim178** [comment]
@cleveranu 
Does it have a deadline to complete this task ?

**Comment by cleveranu** [comment]
complete and submit it asap!

**Comment by nikim178** [comment]
Sure

**Comment by nikim178** [comment]
hey @cleveranu I have doubt 
what exactly I need to Build?  A wikepedia page with same structure and what content should be there on that page ? or i have to create a search feature of wikipedia?
please guide me that would be a great help.
thank you
