### ISSUE TITLE
[GSSoC] Number Guesser Game

### ISSUE THREAD

**Issue by PoulavBhowmick03** [ssitvit/Code-Canvas#110]
Add a number guesser game. The game is simple. You will have to enter a random number and see if the system has guessed the same number
![image](https://github.com/ssitvit/Code-Canvas/assets/133862694/0b496cf2-6b1d-4f38-adad-5df59a28f440)

**Comment by iamvbenz49** [comment]
i would like to work on this project

**Comment by iamvbenz49** [comment]
i would like to work on this issue

**Comment by Dharmesh177** [comment]
assigned to @iamvbenz49 
Complete this within 1 week and
Include a screenshot or deploy link to assess your project and thereafter include your project in the main code with the following contributing.md guidelines.

**Comment by PoulavBhowmick03** [comment]
@Dharmesh177 Sorry? but I created this issue , with the screenshot... Shouldn't it be assigned it to me?

**Comment by iamvbenz49** [comment]
I'm working on it

**Comment by Dharmesh177** [comment]
Sorry @PoulavBhowmick03 You can make PR Will consider accordingly.

**Comment by Dharmesh177** [comment]
@iamvbenz49 Complete it immediately

**Comment by iamvbenz49** [comment]
ok!! I finished the game just now :), it would be easier for us if there's some contributing guidelines
