### ISSUE TITLE
Missing Issue Template in Repository

### ISSUE THREAD

**Issue by Nishitbaria** [ssitvit/Code-Canvas#118]
**Description:**

I noticed that the repository does not have an issue template. Having an issue template can greatly improve the clarity and consistency of issue reports, making it easier for contributors and maintainers to understand and address the problems or feature requests effectively.

**Comment by shashank-23002** [comment]
Can you please describe the type of template you would like to add such as a bug template or a new feature template?
As an example i have created a pull request of a general issue template. You can verify and merge it and assign this issue to me.

**Comment by Nishitbaria** [comment]
`here are three templates that I want include:`

`Issue Template:` This template enables users to create well-structured issue reports by providing sections for a concise title, detailed description, steps to reproduce (if applicable), expected behavior, actual behavior, additional information, and environment details.
`Feature Request Template:` The feature request template allows users to outline their desired features with clarity, including sections for a clear feature description, expected benefits, and any additional context or information.
`Documentation Template:` This template facilitates the creation of comprehensive documentation by providing a structured format, including sections for an introduction, usage instructions, examples, and other relevant details.

**Comment by shashank-23002** [comment]
The following three templates have been added and committed. You can review it in pull request @Dharmesh177 @Shreyaar12 @artimanputra .

**Comment by Nishitbaria** [comment]
### 

**if you have created then I am close the issue**
