### ISSUE TITLE
[GSSoC'23] New Project : Blackjack Game

### ISSUE THREAD

**Issue by palakag29** [ssitvit/Code-Canvas#124]
The Blackjack project consists of `HTML, CSS, and JavaScript` code that allows users to play the game directly in their web browser. The game follows the traditional rules of Blackjack, where players aim to achieve a card sum as close to 21 as possible without exceeding it.

**Comment by palakag29** [comment]
Waiting for your reply to start the project asap @Shreyaar12 @Dharmesh177 @artimanputra !!

**Comment by Dharmesh177** [comment]
assigned to @palakag29 
Complete this within 10 days and
Include a screenshot or deploy link to assess your project and thereafter include your project in the main code with the following contributing.md guidelines.

**Comment by palakag29** [comment]
Hi @artimanputra @Dharmesh177 @Shreyaar12

* Please review my pull request #217
