### ISSUE TITLE
Food corner page can be more appealing

### ISSUE THREAD

**Issue by DeepikaChauhan09** [ssitvit/Code-Canvas#140]
- Can add a rating for each dish in the food corner page.

- header of the food corner page can be more appealing
- for each dish, can include feature which tells about the different things(like salad, picked etc) that come along with that dish

-  can add hover effect in header's cart nd food corner icon

**Comment by Dharmesh177** [comment]
assign to u complete it in 1 week and follow contributing.md file guide..
