### ISSUE TITLE
add a card for top 10 rated netflix series of 2023 and their details

### ISSUE THREAD

**Issue by DeepikaChauhan09** [ssitvit/Code-Canvas#146]
> Please assign me this issue

> . in details, can add its name, rating, overview and etc

**Comment by Dharmesh177** [comment]
assign to u complete it in 1 week and follow contributing.md file guide..

**Comment by ChavvaNarayana** [comment]
Hey @Dharmesh177 I would like to work on it

**Comment by ChavvaNarayana** [comment]
@Dharmesh177  Please review my PR and provide feedback.
