### ISSUE TITLE
Love Calculator Game

### ISSUE THREAD

**Issue by whiteknight16** [ssitvit/Code-Canvas#168]
A love calculator game made using HTML CSS and JS that returns a love score based on certain parameters. Kindly assign me this issue

**Comment by artimanputra** [comment]
assigned to @whiteknight16 
Complete this within 3-4 days and
Include a screenshot or deploy link to assess your project and thereafter include your project in the main code following contributing.md guidelines

**Comment by whiteknight16** [comment]
Sure here is github pages link:https://whiteknight16.github.io/Love-Result-Preditor/
and this is repo link https://github.com/whiteknight16/Love-Result-Preditor kindly check thankyou

**Comment by artimanputra** [comment]
> 

Ok that's great, Make a PR and make sure to add a related card in Index.html
