### ISSUE TITLE
Remove Green Background of the cart

### ISSUE THREAD

**Issue by rolikaagarwal** [ssitvit/Code-Canvas#17]
I want to remove the green background of the add to cart and align it according to the cart image and text.

![image](https://github.com/ssitvit/Code-Canvas/assets/81984963/c54d6c9c-effb-4e11-af1b-59757d18667c)

**Comment by rolikaagarwal** [comment]
I'm unable to push my changes . It's showing this error of permission denied. Can you please help me with this?
![image](https://github.com/ssitvit/Code-Canvas/assets/81984963/3cc261ed-cd4f-4598-a553-824bea22c29c)

**Comment by Dharmesh177** [comment]
Assign to You Start working and complete in 1 week 
Follow contributing.md guide for successful PR merge.
Happy Coding!!
