### ISSUE TITLE
Add Animation: Confetti 

### ISSUE THREAD

**Issue by its-me-abhishek** [ssitvit/Code-Canvas#170]
Add an animation of confetti falling when a button is pressed. This will be made using HTML, CSS, JS.

Please assign this issue under GSSOC

**Comment by artimanputra** [comment]
assigned to @its-me-abhishek 
Complete this within 3-4 days and
Include a screenshot or deploy link to assess your project and thereafter include your project in the main code following contributing.md guidelines
