### ISSUE TITLE
new project: Image editor

### ISSUE THREAD

**Issue by rohanmittal1163** [ssitvit/Code-Canvas#172]
hi @Dharmesh177, I want to share my image editor website with your github repo.
pls assign me with this new feature to your upcoming project
thank you in advance 
![image](https://github.com/ssitvit/Code-Canvas/assets/97821844/7d856ffc-ee1c-4f33-a944-a1ac3bad9c21)

**Comment by artimanputra** [comment]
assigned to @rohanmittal1163 
Try to improve it and then Include a screenshot or deploy link to assess your project and thereafter include your project in the main code with the following contributing.md guidelines
