### ISSUE TITLE
[GSSOC'23] GUESS WORD GAME

### ISSUE THREAD

**Issue by rohanmittal1163** [ssitvit/Code-Canvas#174]
hi @Dharmesh177 ,
i want to create a word guessing game. with timer and amazing ui
pls assign me with this issue as a GSSOC'23 contributor
thank you in advance

**Comment by artimanputra** [comment]
assigned to @rohanmittal1163 
Complete this within 1 week and
Include a screenshot or deploy link to assess your project and thereafter include your project in the main code with following the contributing.md guidelines
