### ISSUE TITLE
reaction tester game how fast you are?

### ISSUE THREAD

**Issue by Sushilverma002** [ssitvit/Code-Canvas#175]
about this it is a reaction tester game like how fast player can click the screen boxes and circle.
![image](https://github.com/ssitvit/Code-Canvas/assets/114687502/8e2c9a5b-1903-41d6-8fe1-17efa92eb56b)

**Comment by artimanputra** [comment]
> about this it is a reaction tester game like how fast player can click the screen boxes and circle. ![image](https://user-images.githubusercontent.com/114687502/241481879-8e2c9a5b-1903-41d6-8fe1-17efa92eb56b.png)

assigned to @Sushilverma002 
Try to improve it and then Include a screenshot or deploy link to assess your project and thereafter include your project in the main code with following the contributing.md guidelines

**Comment by Sushilverma002** [comment]
here the updated one .
![image](https://github.com/ssitvit/Code-Canvas/assets/114687502/d088599a-9c5c-4872-8aef-74b90c81983b)

**Comment by Sushilverma002** [comment]
here it is.
https://github.com/ssitvit/Code-Canvas/assets/114687502/b51548ec-1878-48d2-bab0-f765c79a4a41

**Comment by Sushilverma002** [comment]
ma'am can u please do me a favor can you please check on more issue #176 on that i have added a favicon.

**Comment by Dharmesh177** [comment]
You are generating same issue of single game now move forwqard to other project
