### ISSUE TITLE
adding favicon on the main index.html

### ISSUE THREAD

**Issue by Sushilverma002** [ssitvit/Code-Canvas#176]
favicon show website more attractive.

**Comment by Dharmesh177** [comment]
assigned to @Sushilverma002 
Complete this within 5 days and
Include a screenshot or deploy link to assess your project and thereafter include your project in the main code with the following contributing.md guidelines.

**Comment by artimanputra** [comment]
> ![favicon-32x32](https://user-images.githubusercontent.com/114687502/241991350-9e570a5d-9bdb-45bb-ad1d-f99562e335ee.png) This favicon i create here 'Cc' in favicon are initials of are web site . I took black white combination as are website theme is similar to the favicon theme. @Dharmesh177

Sure it looks good, make a PR for this

**Comment by Sushilverma002** [comment]
@Dharmesh177 @artimanputra please check the PR
