### ISSUE TITLE
Tic-tac-Toe crashes when match becomes a draw

### ISSUE THREAD

**Issue by iamvbenz49** [ssitvit/Code-Canvas#178]
[Screencast from 2023-05-28 03-54-28.webm](https://github.com/ssitvit/Code-Canvas/assets/93785572/03df8c78-ea10-462a-bf20-3bc1a38cb1ad)

**Comment by artimanputra** [comment]
> Screencast.from.2023-05-28.03-54-28.webm

The same issue is already, you can choose another project and create a new issue.

**Comment by iamvbenz49** [comment]
when match becomes s draw application crashes, I think you didn;t get me
