### ISSUE TITLE
Want to add a Responsive To-Do list

### ISSUE THREAD

**Issue by Anushka-gupta496** [ssitvit/Code-Canvas#179]
I wish to add a project on To-Do list with features such as adding a new item to list, checking an item after completing it and crossing it and deleting an item. 
Please assign me this issue under GSSOC'23.
@Dharmesh17 @artimanputra @Shreyaar12 

![Preview_of_to-do list](https://github.com/ssitvit/Code-Canvas/assets/98311688/9d7e65f1-6f38-462b-a987-7271b0d17ca5)

**Comment by artimanputra** [comment]
> I wish to add a project on To-Do list with features such as adding a new item to list, checking an item after completing it and crossing it and deleting an item. Please assign me this issue under GSSOC'23. @Dharmesh17 @artimanputra @Shreyaar12
> 
> ![Preview_of_to-do list](https://user-images.githubusercontent.com/98311688/241530113-9d7e65f1-6f38-462b-a987-7271b0d17ca5.png)

a TO DO list project is already added in the website you can create another project
