### ISSUE TITLE
[GSSoC '23] A Rock Paper Scissors Game

### ISSUE THREAD

**Issue by PoulavBhowmick03** [ssitvit/Code-Canvas#183]
A single player rock paper scissors game  using HTML, CSS and Javascript

**Comment by PoulavBhowmick03** [comment]
@Dharmesh177 can you assign this to me? I don't see any other such issues

**Comment by artimanputra** [comment]
> A single player rock paper scissors game using HTML, CSS and Javascript

assigned to @PoulavBhowmick03  
Complete this within 1 week and
Include a screenshot or deploy link to assess your project and thereafter include your project in the main code with following the contributing.md guidelines
