### ISSUE TITLE
Flappy Bird Game

### ISSUE THREAD

**Issue by shubham-shinde-442** [ssitvit/Code-Canvas#19]
As a Contributor in GSSoC"23 , I Would like to Create Flappy Bird Game using JavaScript , HTML , CSS . Can You Assign Me This Game ?

**Comment by Dharmesh177** [comment]
Assign to @shubham-shinde-442 Start working and complete in 1 week 
Follow contributing.md guide for successful PR merge.
Happy Coding!!

**Comment by shubham-shinde-442** [comment]
Sure
