### ISSUE TITLE
Multiplication website

### ISSUE THREAD

**Issue by Abhinavcode13** [ssitvit/Code-Canvas#193]
About
A multiplication app using HTML, CSS, and JavaScript is a web application that allows users to practice and improve their multiplication skills. The application typically consists of a user interface that displays multiplication questions and allows users to enter their answers

Please assign me this issue @artimanputra @Dharmesh177 @Shreyaar12 under gssoc 23

screenshot of website:

![image](https://github.com/ssitvit/Code-Canvas/assets/126642111/0e0ab073-b9b7-425f-900d-7757087f1bb8)

**Comment by Dharmesh177** [comment]
It is very basic things doesn't look like project include some more feature
