### ISSUE TITLE
Candy crush game gssoc 23

### ISSUE THREAD

**Issue by Abhinavcode13** [ssitvit/Code-Canvas#200]
please assign me this issue @Dharmesh177

**Comment by Abhinavcode13** [comment]
![image](https://github.com/ssitvit/Code-Canvas/assets/126642111/122f3aa4-f576-4110-9748-3eeed77fe100)

**Comment by Abhinavcode13** [comment]
look out this I'm going to add @Dharmesh177

**Comment by Abhinavcode13** [comment]
hello any update please ?? @artimanputra

**Comment by samikshatrivedi007** [comment]
please assign this task to me , I am really good in it #200
