### ISSUE TITLE
[New Game]: Memory Card Game

### ISSUE THREAD

**Issue by Anushka-gupta496** [ssitvit/Code-Canvas#201]
Memory card game is a simple matching cards game in which all the cards are flipped backside on a surface and two cards are flipped face up over each turn. The objective of this game is to match all the pairs of cards.
Please assign it under GSSOC'23.
@Dharmesh177 @artimanputra

**Comment by artimanputra** [comment]
> Memory card game is a simple matching cards game in which all the cards are flipped backside on a surface and two cards are flipped face up over each turn. The objective of this game is to match all the pairs of cards. Please assign it under GSSOC'23. @Dharmesh177 @artimanputra

assigned to @Anushka-gupta496 
Complete this within 10 days and
Include a screenshot or deploy link to assess your project and thereafter include your project in the main code with the following contributing.md guidelines.
