### ISSUE TITLE
[GSSoC '23] Contributing a Shopping Cart Project to Code-Canvas

### ISSUE THREAD

**Issue by debsouryadatta** [ssitvit/Code-Canvas#202]
### Description
I am making this issue to contribute a shopping cart project build with vanilla JS to Code-Canvas open source project.
### Objective 
By contributing this project I want to help beginners build and learn more JavaScript Projects and have a good understanding in JavaScript, so this website will be a great project for everyone to have more knowledge about JS.
So Please assign this to me under GSSoC'23 @Dharmesh177

**Comment by Dharmesh177** [comment]
assign to @debsouryadatta while making PR follow contirbuting.md guidelines and complete it in 1 week

**Comment by debsouryadatta** [comment]
Sure ✌️

> assign to @debsouryadatta while making PR follow contirbuting.md guidelines and complete it in 1 week
