### ISSUE TITLE
Rock Paper Scissors game

### ISSUE THREAD

**Issue by Vivek-C-Shah** [ssitvit/Code-Canvas#221]
Description:
This GitHub issue is created to address the integration of a Rock Paper Scissors game in the CodeCanvas open source project.

Objective:
The objective of this issue is to enhance CodeCanvas by integrating a Rock Paper Scissors game feature. This will provide users with an interactive and enjoyable gaming experience within the web application.

**Comment by palakag29** [comment]
#183  it was already done by someone else.
Check the existing issues before creating new

**Comment by Vivek-C-Shah** [comment]
Okay, thanks.
