### ISSUE TITLE
Improving the index.html file

### ISSUE THREAD

**Issue by harshsingh32** [ssitvit/Code-Canvas#23]
I would like to improve the index.html file of travel_landing project. I would like to add features in it and make it more expressive and engaging for the users.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by Sayan2k3** [comment]
I would like to work in this project of improving the index.html file.I have skimmed over the index page and  clearly modifications can be done,i would like to modify the index page assign me with the isssue
