### ISSUE TITLE
[GSSoC'23] Morse Code Translator

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [ssitvit/Code-Canvas#234]
**Description**

- This project will convert entered value into morse code.
- This project will make by using HTML, CSS and JS and give it a very attractive and fancy look.

**Comment by Avdhesh-Varshney** [comment]
Sirs @Dharmesh177 @artimanputra , please /assign this task to me to contribute under GSSoC'23.

**Comment by Dharmesh177** [comment]
Sure !! 
Assigned to u. Complete it in 10 Days and follow contributing.md  Guide
