### ISSUE TITLE
Add A Creative Footer Section

### ISSUE THREAD

**Issue by deepeshgupta3257** [ssitvit/Code-Canvas#237]
It's not a problem but to have a good footer makes a website look cool and easy for a user to get the details about the social media handles and many more important part from the bottom also.
I have a quite good solution for your website to add a attractive and informative footer section which will consist of all the important information about the website and all the official social media handles. 

So, please assign me this issue under GSSOC'23 so, that I can start working on this issue

**Comment by Dharmesh177** [comment]
assign to @deepeshgupta3257 Complete it in 1 Week and Follow contirbuting.md Guidelines. Include screenshot to assess your work.
