### ISSUE TITLE
[Feature] : A blog landing page for forest travelers and trekking. 

### ISSUE THREAD

**Issue by raj03kumar** [ssitvit/Code-Canvas#251]
- A forest blog landing page for travelers and trekkers.
- With image slider
- CSS Grid implementation
- Responsive
- Looks something like this
![image](https://github.com/ssitvit/Code-Canvas/assets/92293392/55dbf048-136d-4607-a297-6f754907b7af)
![image](https://github.com/ssitvit/Code-Canvas/assets/92293392/495ae21a-fc42-463b-965f-aad3d206184f)

- Kindly assign this issue to me under GSSoc '23

**Comment by Shreyaar12** [comment]
Merged
