### ISSUE TITLE
Fixing the projects cards & alignment of the heading 

### ISSUE THREAD

**Issue by tanayvaswani** [ssitvit/Code-Canvas#26]
The cards don't have a proper border-radius, we can see a white portion appearing of the corners and it's not looking good. Also, the heading named "Projects" is not centered properly, fixing this issue will make the website look prettier. 

![Screenshot (18)](https://github.com/ssitvit/Code-Canvas/assets/114291962/958c177d-eb9f-40af-a462-631717d4c302)

**Comment by tanayvaswani** [comment]
@cleveranu Can you please add good-first-issue and GSSoC labels?

**Comment by cleveranu** [comment]
good work @tanayvaswani.
I am closing this issuse now.
