### ISSUE TITLE
Expense Tracker

### ISSUE THREAD

**Issue by Shreyaar12** [ssitvit/Code-Canvas#263]
Completion date : 20 June '2023

1. Investment analysis and tracking 

2. Daily expense monitoring

These things should be included in this

**Comment by palakag29** [comment]
@Shreyaar12  Please assign this issue to me

**Comment by sagnik-p** [comment]
I would like to work on this
Please assign

**Comment by Shreyaar12** [comment]
Assigned it to you!! Kindly complete within deadline and refer contributing.md and readme.md. 
Happy Coding!!
