### ISSUE TITLE
Expense Tracker

### ISSUE THREAD

**Issue by Shreyaar12** [ssitvit/Code-Canvas#264]
Budgeting and bill reminder should be there. 

Completion date: 20th June'23

**Comment by palakag29** [comment]
@Shreyaar12  Please assign this issue to me

**Comment by Shreyaar12** [comment]
Kindly complete before 20 june

You can use html css js, jquery and any orher frameworks for css like bootstrap, tailwind or scss, sass etc

**Comment by rudrakushwaha** [comment]
Hey I would like to work on this issue. Please assign it to me.

**Comment by palakag29** [comment]
@Shreyaar12 i have made an pull request. Please review and merge #346

**Comment by palakag29** [comment]
@Shreyaar12 i have made an pull request. Please review and merge

- https://github.com/ssitvit/Code-Canvas/pull/350

**Comment by Shreyaar12** [comment]
Merged
