### ISSUE TITLE
[New Project]: Spotify Clone

### ISSUE THREAD

**Issue by shambhavisingh011** [ssitvit/Code-Canvas#266]
I wish to add a clone displaying the home page of Spotify.
Here is a screenshot of the website. Kindly take a look at this.
Please assign me it under GSSOC'23.
@Dharmesh177 @artimanputra 

![final_preview](https://github.com/ssitvit/Code-Canvas/assets/121101577/95b66e17-1327-4df8-b81c-66807eef162a)

**Comment by shellyverma** [comment]
Hey @dhairyaostwal @nandurijv, I would like to add Spotify Clone.
I can resolve this issue. I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23.

**Comment by Dharmesh177** [comment]
Sure !! 
Assigned to @shambhavisingh011  . Complete it in 10 Days and follow contributing.md  Guide
