### ISSUE TITLE
Candy Crush Game

### ISSUE THREAD

**Issue by PoulavBhowmick03** [ssitvit/Code-Canvas#270]
Create a Candy Crush Game using HTML, CSS and Javascript
User will be able to drag the elements to match 3 of them and get points

![image](https://github.com/ssitvit/Code-Canvas/assets/133862694/0de9f4e9-f6f6-4124-9ec9-35c57c94224e)

**Comment by PoulavBhowmick03** [comment]
@Dharmesh177 pls check

**Comment by shellyverma** [comment]
Hey @dhairyaostwal @nandurijv , I would like Create a Candy Crush Game using HTML, CSS and Javascript.
 I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23

**Comment by PoulavBhowmick03** [comment]
@cleveranu Can this pls be assigned ?

**Comment by PoulavBhowmick03** [comment]
@Dharmesh177

**Comment by Dharmesh177** [comment]
Sure !! 
Assigned to u. Complete it in 10 Days and follow contributing.md  Guide
