### ISSUE TITLE
Add a real time character counter

### ISSUE THREAD

**Issue by Uma-95** [ssitvit/Code-Canvas#282]
In this project when a paragraph or some text is entered, it shows the number of characters added and the number of characters that can still be added so as not to exceed the maximum character limit.
Techstack:HTML,CSS,JS
(As a part of GSSOC'23)

**Comment by Uma-95** [comment]
@Shreyaar12 @cleveranu could you please assign this issue to me as a part of GSSOC'23.

**Comment by Dharmesh177** [comment]
This is one program not frontend Project or small application. 
Add some feature
