### ISSUE TITLE
Pomodoro and Productivity System [GSSOC'23]

### ISSUE THREAD

**Issue by smty2018** [ssitvit/Code-Canvas#283]
Want to add a productivity system with Pomodoro Timer and to do planner

Completion time: 7 days (maximum)

**Comment by smty2018** [comment]
@Shreyaar12 @Dharmesh177 Please assign me this issue under GSSOC'23

**Comment by Shreyaar12** [comment]
Sure, assigned to you @smty2018 
Kindly complete on time and follow contributing.md and readme.md 
Happy Coding!!
