### ISSUE TITLE
[Feature Request] : Work on UI of the website , Landing page

### ISSUE THREAD

**Issue by itsmohit097** [ssitvit/Code-Canvas#284]
**Description**
The current UI is  not attractive. 

**Describe briefly how you would implement this enhancement.**
I already created a figma design for the site. I will use the html and tailwind css to implement it.
You can see it here :
https://www.figma.com/file/v7nlXgmMJQFr1WzhwcgBX7/CodeCanvas?type=design&node-id=0%3A1&t=69ipxTJCXsiVZWmD-1

**Additional context or screenshots**
![cc](https://github.com/ssitvit/Code-Canvas/assets/125040386/096fbec0-fcba-4a1f-8cb8-3ff9cca3fee7)

Are you contributing for a program?
GSSOC'23 

If you're interested. Let me know your thoughts
@Shreyaar12  @cleveranu

**Comment by Dharmesh177** [comment]
@Shreyaar12 Need your approval as well.
Myside We should go with this addressing this issue.

**Comment by itsmohit097** [comment]
@Shreyaar12 please respond
