### ISSUE TITLE
Responsive parallax Portfolio page

### ISSUE THREAD

**Issue by PoulavBhowmick03** [ssitvit/Code-Canvas#285]
A responsive parallax and interactive portfolio page

![image](https://github.com/ssitvit/Code-Canvas/assets/133862694/f5c141a4-e793-477a-b27b-2dd8740e2e89)

![image](https://github.com/ssitvit/Code-Canvas/assets/133862694/93150176-09c5-4c7a-8a28-7766161fcf10)

![image](https://github.com/ssitvit/Code-Canvas/assets/133862694/0b915723-541b-4f9f-9497-21f07d030170)

**Comment by PoulavBhowmick03** [comment]
@Dharmesh177 @cleveranu  Can it please be assigned

**Comment by Dharmesh177** [comment]
@PoulavBhowmick03 Portfolio website already there on our repo
