### ISSUE TITLE
[New Project]: BMI Calculator

### ISSUE THREAD

**Issue by Anushka-gupta496** [ssitvit/Code-Canvas#293]
I wish to add a project on BMI Calculator. This project will take height and weight as input from the user and will calculate BMI. It will also show the user, the category they falls in:
1. Normal Range
2. Underweight
3. Overweight

I'll be making this project using HTML, CSS and JavaScript.
Kindly assign me this issue under GSSOC'23. 
@Dharmesh177

**Comment by Dharmesh177** [comment]
Sure assign to u 
Complete it in 1 week and follow contributing.md file guide while making PR
Happy Coding !!
