### ISSUE TITLE
[Bug]: Hover effect defect

### ISSUE THREAD

**Issue by SoumyadeepOSD** [ssitvit/Code-Canvas#30]
### Clicking in between the cards should not look like this. It should be made in such a way that only hovering on the specific card will be active keeping rest of all blur

![image](https://github.com/ssitvit/Code-Canvas/assets/115442240/3e58dc52-91b8-4dad-8600-f496b1c08325)

**Comment by SoumyadeepOSD** [comment]
I want to work on this issue under GSSOC 2023. Please assign it to me

**Comment by cleveranu** [comment]
Already improved
