### ISSUE TITLE
Whack a mole game

### ISSUE THREAD

**Issue by lakhan06** [ssitvit/Code-Canvas#322]
IN this game a mole will come out of the pipes and if you click on it then your points will increase .
But also a plant will come so if you click on the plant then game will over .
Every correct click on the mole will increase your point by 10.
![image](https://github.com/ssitvit/Code-Canvas/assets/119161467/87b43813-2676-4a84-8ade-731d8ba3207c)

@Shreyaar12 please assign me this issue

**Comment by Dharmesh177** [comment]
Already submitted to another repo dont do this again else you will disqualify form gssoc'23

**Comment by lakhan06** [comment]
> Already submitted to another repo dont do this again else you will disqualify form gssoc'23

ok
