### ISSUE TITLE
Unit_Converter

### ISSUE THREAD

**Issue by apu52** [ssitvit/Code-Canvas#338]
### Hello Sir ,👋
I am Arpan Chowdhury, a aspiring Web developer.🤖 I want to add my **Unit Converter** project under GSSoC'23.😁We all use this most used mobile application. I have made it with the use of HTML,CSS & JS.

**Expected behavior**

### Description
I have made a very basic Unit Converter where it just changes **foot to inch** & Vice-versa. Anyone can input integer or decimal. & there is also a up🔼 & down 🔽arrow. 

**Screenshots (optional)**

https://github.com/apu52/Unit-converter/assets/114172928/0b4d16dc-fbf8-4e7a-a63e-04bdb624aa18

**Additional context (optional )**

Please **Assign** me the issue🙏UNDER **gssoc'23**

**Comment by avoxaya** [comment]
I know how to make an interactive Unit Converter and have worked with the same previously. Please assign me this issue in GSSoC'23.

**Comment by adarsh-aur** [comment]
I can easily make an interactive unit converter using HTML, CSS, JS.
Could you assign it to me?

**Comment by apu52** [comment]
Sir/Ma'am please assign me the issue.
