### ISSUE TITLE
Stopwatch

### ISSUE THREAD

**Issue by apu52** [ssitvit/Code-Canvas#339]
### Project title
**Stopwatch**

### Hello Sir ,👋
I am Arpan Chowdhury, a aspiring Web developer.🤖 I want to add my **Stopwatch⏰** project under GSSoC'23.😁We all use this most used mobile application. I have made it with the use of **HTML,CSS & JS**. 
### Description
It has  buttons with start, reset and pause . It also shows  hour, minute, second & millisecond⏱️.
### Screenshots
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/114172928/3de28b16-4e0c-4259-a01d-a9a744380446)
Please **Assign** me the issue🙏under **GSOC'23**

**Comment by avoxaya** [comment]
I know how to make an interactive stop watch and have worked with the same previously. Please assign me this issue in GSSoC'23.

**Comment by adarsh-aur** [comment]
I can easily make an interactive stopwatch using HTML, CSS, JS.
Could you assign it to me?

**Comment by apu52** [comment]
Sir/Ma'am please assign me the issue.
