### ISSUE TITLE
fix:Read me

### ISSUE THREAD

**Issue by iqrafirdose** [ssitvit/Code-Canvas#344]
I would like to fix the read me, as the contributors are not displaying in the read me file, and the project admin LinkedIn is not aligned properly.
Here  is the screenshot:
![g2](https://github.com/ssitvit/Code-Canvas/assets/114678694/0cecc5cd-0e03-4dba-9ecc-3ecaf1f87321)

**Comment by iqrafirdose** [comment]
Could you please assign the issue under gssoc?

**Comment by sujal402** [comment]
I am interested to make readme good looking so reques to assign this issue  to me under gssoc23
