### ISSUE TITLE
[GSSoC'23] Solar system model

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [ssitvit/Code-Canvas#348]
Title - Solar System Model

- Front end project
- Creating using HTML, CSS and JS
- Shows rotation of different planets around sun
- Tell about the some information on click like own mass, distance from the sun, etc.
- This will be very helpful from the point of view of children to learn about planets, solar system, etc. using visualization.

**Comment by Avdhesh-Varshney** [comment]
@cleveranu @Shreyaar12 @artimanputra @Dharmesh177 please assign this task to me to create a animated and speakable model using front end languages and contribute under GSSoC'23 program

**Comment by Shreyaar12** [comment]
@Avdhesh-Varshney Assigning this to you make sure to submit it within 10 days and refer guidelines as well. 
Happy Coding!

**Comment by Shreyaar12** [comment]
@Avdhesh-Varshney
