### ISSUE TITLE
[GSSoC'23] Periodic Table of Elements using HTML, CSS and JS

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [ssitvit/Code-Canvas#366]
- Front-end Project
- Creating using HTML, CSS and JS
- Hovering effect on the elements of periodic table
- Attractive User interface with colourful gradient background
- Responsiveness towards mobile devices
- Showing data of that element on hovering like atomic number, atomic mass, full name, etc.
- This will help students to learn periodic table in just one click on the mobile or any other devices.

**Comment by Avdhesh-Varshney** [comment]
@cleveranu @Shreyaar12 @artimanputra @Dharmesh177 
Please assign this project to me for a valuable contribution in this repository under GSSoC'23 program
/assign

**Comment by Avdhesh-Varshney** [comment]
@Dharmesh177 @cleveranu @Shreyaar12 @artimanputra 
Sirs, please assign this project to me to work on it under GSSoC'23 program

**Comment by Avdhesh-Varshney** [comment]
@Dharmesh177 @cleveranu @Shreyaar12 @artimanputra 
Sirs, I have done with this project and want to create a pull request for a valuable contribution under GSSoC'23 program

So, I requested to you please /assign it to me

**Comment by Avdhesh-Varshney** [comment]
@Dharmesh177 @artimanputra @Shreyaar12 @cleveranu 
Sirs, I have done with this project and want to create a pull request to contribute under GSSoC'23 program

Screenshot
![Periodic_Table](https://github.com/ssitvit/Code-Canvas/assets/114330097/54c22bd1-d620-45aa-a93b-8d98af30e156)


So sirs, please i requested to you, assign this project to me

**Comment by Dharmesh177** [comment]
span as already submitted on other project
