### ISSUE TITLE
GSSoC'23 Enhacement : Add Geolocation Feature for Weather Website

### ISSUE THREAD

**Issue by palakag29** [ssitvit/Code-Canvas#370]
## Description:
I would like to request the addition of a geolocation feature to the existing weather website. Currently, it allows users to search for weather information based on a specific city, but it would be beneficial to also provide weather data based on the user's current location.

## Feature Request Details:

1. Add a "Get Weather for Current Location" button to the app interface.
2. Implement geolocation logic in JavaScript to fetch the weather data based on the user's latitude and longitude.
3. Display the weather information for the user's current location in the app's UI.
4. Handle cases where geolocation is not supported by the browser and provide appropriate error messages.

By adding the geolocation feature, users will have the option to quickly get weather information for their current location without having to manually search for a specific city.

Please let me know if you need any further information or clarification. Thank you for considering this feature request.

**Comment by Dharmesh177** [comment]
assign to u start working !!
complete it in 7 days and follow contributing.md file guidance for successful PR merge

**Comment by palakag29** [comment]
@Dharmesh177 Please review and merge the pull request.  #391
