### ISSUE TITLE
A Tribute Webpage

### ISSUE THREAD

**Issue by shambhavisingh011** [ssitvit/Code-Canvas#375]
I want to add a webpage specially designed to give tribute to noble people built using HTML and CSS.
Please assign me it under GSSOC'23.
@Dharmesh177 @artimanputra
Here is the screenshot of the page-
![image](https://github.com/ssitvit/Code-Canvas/assets/121101577/6b52c013-d323-4708-9f9f-a3f6fa1b8359)

**Comment by Dharmesh177** [comment]
sure assign to u !! start working and complete it in 10 days 
follow contributing.md guide for successful PR merge.
happy coding !!
