### ISSUE TITLE
Job Application Page

### ISSUE THREAD

**Issue by shambhavisingh011** [ssitvit/Code-Canvas#376]
I want to contribute by adding a job application page that is built using HTML and CSS.
Here is a screenshot of the website. Kindly take a look at this.
Please assign me it under GSSOC'23.
@Dharmesh177 @artimanputra
![image](https://github.com/ssitvit/Code-Canvas/assets/121101577/6720e2fa-5072-4055-912b-4a2679691708)

**Comment by Dharmesh177** [comment]
sure assign to u !! start working and complete it in 10 days 
follow contributing.md guide for successful PR merge.
happy coding !!
