### ISSUE TITLE
Amazon clone

### ISSUE THREAD

**Issue by ePSA-eJya** [ssitvit/Code-Canvas#380]
Amazon clone using html,css,javascript.
i an gssoc23 contributor please assign this issue to me @Shreyaar12 @artimanputra @Dharmesh177

**Comment by Dharmesh177** [comment]
assign to u start working !!
complete it in 10 days and follow contributing.md file guidance for successful PR merge

**Comment by ePSA-eJya** [comment]
Ok thanks
