### ISSUE TITLE
New spin the wheel game

### ISSUE THREAD

**Issue by ePSA-eJya** [ssitvit/Code-Canvas#382]
using html,css,javascript.
i am gssoc23 contributor please assign this issue to me @Shreyaar12 @artimanputra @Dharmesh177

**Comment by Dharmesh177** [comment]
assign to u !!
complete it in 1 Week and follow contributing.md file guideance for successful PR merge
Happy Coding 🧑‍💻!!

**Comment by ePSA-eJya** [comment]
thanks
