### ISSUE TITLE
[GSSoC'23] Dots and Boxes Game

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [ssitvit/Code-Canvas#384]
- Front end project
- Tech using HTML, CSS and JS
- Multi player game
- With best sound quality
- Adding attractive and smooth user interface and best experience to the user

We have played this game so many times in our childhood. It's rules are so simple,
More the boxes you have got, more will your score and you will be the winner of this game.

**Comment by Avdhesh-Varshney** [comment]
@artimanputra @Shreyaar12 @Dharmesh177 @cleveranu 
Sirs, please assign this game to me to work on it and give a valuable contribution under GSSoC'23 program
/assign

**Comment by Avdhesh-Varshney** [comment]
@Dharmesh177 @artimanputra @Shreyaar12 @cleveranu 
Sirs, I have done with this project and want to create a pull request to contribute under GSSoC'23 program
So sirs, please assign this project to me

**Comment by Dharmesh177** [comment]
sure assign to u !! start working and complete it in 10 days 
follow contributing.md guide for successful PR merge.
happy coding !!
