### ISSUE TITLE
GSSoC'23 : Add Scoreboard feature in Rock Paper Scissors game

### ISSUE THREAD

**Issue by palakag29** [ssitvit/Code-Canvas#394]
### Description:
I would like to contribute to the Rock Paper Scissors game by adding a scoreboard feature. This feature will enhance the user experience by keeping track of the number of wins, losses, and draws for the user and the CPU. The scoreboard will be displayed after each game result and reset when the game is restarted.

### Features Request

1. Display the user's score (number of wins) on the scoreboard.
2. Display the CPU's score (number of wins) on the scoreboard.
3. Display the number of draws on the scoreboard.
4. Update the scoreboard after each game result.
5. Reset the scoreboard when the game is restarted.

**Comment by palakag29** [comment]
@Dharmesh177 please assign me this issue

**Comment by palakag29** [comment]
@Dharmesh177 I have done this. please assign me so that i can make a pull request

**Comment by Dharmesh177** [comment]
assign to u !!
complete it in 1 Week and follow contributing.md file guideance for successful PR merge
Happy Coding 🧑‍💻!!
