### ISSUE TITLE
New Wordle Game

### ISSUE THREAD

**Issue by ritik48** [ssitvit/Code-Canvas#395]
#### Wordle game
Here user will be displayed blank boxes, and will have to guess the word.
With each guesses the user will be given a hint like:

- if the letter in the guess exists in the original word but is at wrong position, then it's color will change to yellow.
- if the letter in the guess exists in the original word and is at a right position, then it's color will change to green.

#### Features:
- flexibility in selecting word length
- easy, medium and tough category options
- there will be fixed number of guesses. and based on in how many guess user figured out the word, score will be given.

#### Please assign this issue to me

**Comment by Dharmesh177** [comment]
Assign to u !! 
complete in 1 week and Follow contributing.md guidelines for successful PR merge.
Happy Coding !!
