### ISSUE TITLE
[GSSOC'23] Improving the Portfolio Project

### ISSUE THREAD

**Issue by vishnuprasad2004** [ssitvit/Code-Canvas#398]
**Describe the Improvement**
Adding Style and Navigation Bar in the Static Template Portfolio
 - Adding Icons instead of Text links for accounts in the footer
- Adding a Navbar to direct to parts of the portfolio 
- Changing the font 
- Adding an avatar image

**Comment by Dharmesh177** [comment]
sure assign to u !! start working and complete it in 10 days 
follow contributing.md guide for successful PR merge.
happy coding !!
