### ISSUE TITLE
GSSoC'23 : Add Random Fact Generator Project

### ISSUE THREAD

**Issue by palakag29** [ssitvit/Code-Canvas#402]
## Random Fact Generator

This project is a Random Fact Generator that displays interesting and random facts to the user. Each time the user clicks the "Generate Fact" button, a new fact is randomly and displayed on the page.

### Tech Stack

- HTML
- CSS
- JavaScript

### Expected Behavior

When the user clicks the "Generate Fact" button, the application should select a random fact from the list and display it on the page.

**Comment by palakag29** [comment]
@Dharmesh177 Please assign me this issue

**Comment by Dharmesh177** [comment]
sure assign to u !! start working and complete it in 10 days 
follow contributing.md guide for successful PR merge.
happy coding !!

**Comment by palakag29** [comment]
@Dharmesh177 @Shreyaar12 @artimanputra I have made a pull request. Please review and merge. Also add appropriate labels to it.
