### ISSUE TITLE
[Docs] Incorrect direction: "Contributors.md" Should Be "Contributing.md"

### ISSUE THREAD

**Issue by jfmartinz** [ssitvit/Code-Canvas#410]
In the current "contribute" section of the repository, there is an error in directing contributors to the appropriate documentation. The sentence states, "for contribution guidelines," but clicking on the "Contributors.md" file only displays the list of contributors, rather than the actual guidelines for contributing. To address this confusion and improve clarity, the correct file that should be linked is "contributing.md," which contains the guidelines for contributing.

![image](https://github.com/ssitvit/Code-Canvas/assets/129386460/d08d9b79-36d0-4136-9222-578b44870f6d)

assign this to me under gssoc23

What do you think?

**Comment by jfmartinz** [comment]
@Dharmesh177  can you check?

**Comment by jfmartinz** [comment]
@Shreyaar12 can you check?

**Comment by jfmartinz** [comment]
@Shreyaar12 @Dharmesh177 can you check?

**Comment by Dharmesh177** [comment]
assign to u start working and complete it in 1 week.
follow contributors.md guide for successful merge.
Happy Coding!!
