### ISSUE TITLE
OLX Clone website

### ISSUE THREAD

**Issue by PoulavBhowmick03** [ssitvit/Code-Canvas#411]
A clone of OLX website, using HTML, CSS and Javascript

![image](https://github.com/ssitvit/Code-Canvas/assets/133862694/80d907ca-a820-462a-b720-ec0b781ac46e)

**Comment by PoulavBhowmick03** [comment]
@Dharmesh177 Please assign this

**Comment by PoulavBhowmick03** [comment]
@Dharmesh177 please merge this

**Comment by Dharmesh177** [comment]
sure assign to u !! start working and complete it in 10 days 
follow contributing.md guide for successful PR merge.
happy coding !!
