### ISSUE TITLE
Netflix Website Clone [GSSOC'23]

### ISSUE THREAD

**Issue by Ekam-Bitt** [ssitvit/Code-Canvas#413]
## Netflix Website landing page clone using HTML, CSS, JAVASCRIPT
<img width="1552" alt="Screenshot 2023-06-23 at 6 38 38 PM" src="https://github.com/ssitvit/Code-Canvas/assets/74407205/57d38f25-dfb9-4d0c-8add-8f8fa6968c55">

**@Dharmesh177 Please assign me this**

**Comment by Dharmesh177** [comment]
Already othher working on this
