### ISSUE TITLE
Fixing Tic Tac Toe Game Card

### ISSUE THREAD

**Issue by 5h0ov** [ssitvit/Code-Canvas#415]
The name and category are not showing as in the picture below:
![image](https://github.com/ssitvit/Code-Canvas/assets/83227649/af59aa8e-f935-4ae8-9043-c32c2a99d40d)

I would like to fix it as a contribution to this project under GSSoC '23.

**Comment by Dharmesh177** [comment]
sure assign to u !! start working and complete it in 10 days 
follow contributing.md guide for successful PR merge.
happy coding !!

**Comment by Dharmesh177** [comment]
Work for more points --
Title of projects are changing in length so in some cards its ready but in some its taking whole space.
could u fix it/...

**Comment by 5h0ov** [comment]
@Dharmesh177  i have fixed it in the recent issue I raised! So this issue can be closed now sir.
