### ISSUE TITLE
[GSSoC'23] Bug : The cards are not displaying correctly

### ISSUE THREAD

**Issue by palakag29** [ssitvit/Code-Canvas#420]
## Problem
in the cards, a maximum of 28 card are displayed in the correct place after that the new cards overlaps with the  `content class`. also all the projects are not displayed

## video

https://github.com/ssitvit/Code-Canvas/assets/112793075/d87b34f7-078b-4c5e-946f-560c492f4f99

## TO DO 
1.  Solve the problem mention above so that new cards added can be displayed correctly.
2. Add responsive web design so that
    - 2 cards are displayed when min-width is 540px
    - 3 cards are displayed when min-width is 768px
    - 4 cards are displayed when min-width is 960px
    - 5 cards are displayed when min-width is 1160px
    

https://github.com/ssitvit/Code-Canvas/assets/112793075/eed62837-f751-49f8-bc1c-b5b90368277b

**Comment by palakag29** [comment]
@Shreyaar12  @Dharmesh177  Please assign me this issue

**Comment by Dharmesh177** [comment]
sure assign to u !! start working and complete it in 10 days 
follow contributing.md guide for successful PR merge.
happy coding !!

**Comment by palakag29** [comment]
@Dharmesh177 @Shreyaar12 @artimanputra I have made a pull request. Please review and merge. Also add appropriate labels to it.
