### ISSUE TITLE
Add RGB Riddle Game

### ISSUE THREAD

**Issue by VSatwika** [ssitvit/Code-Canvas#424]
### 🎮 RGB Riddle Game

 - RGB Riddle is a thrilling game that puts your estimation ability and familiarity with the RGB color scheme to
  the test. 
 - Could this issue be assigned to me under GSSoC'23?

### Point down the features

 - In this game, you will be presented with various color swatches, each represented by their RGB values. 
 - Your task is to estimate and select the closest matching color from a set of options provided.
 - The game has 2 levels, easy and hard.
      - On picking hard, you will have to choose the closest match out of 6 options to the given RGB coordinates.
      - On picking easy, you will have to choose the closest match out of 3 options to the given RGB coordinates.

 - It features stunning visuals and a user-friendly interface, allowing you to immerse yourself in a world of captivating colors.
 
 ## Screenshot
<img width="960" alt="RGB_Riddle" src="https://github.com/ssitvit/Code-Canvas/assets/112561024/e79bdd02-b970-492f-bcaa-87d951f5d177">

**Comment by Dharmesh177** [comment]
Already submitted to another repo dont do this again else you will disqualify form gssoc'23
