### ISSUE TITLE
Improve the Footer of the website

### ISSUE THREAD

**Issue by sumitkr2000** [ssitvit/Code-Canvas#427]
Hey, I want to improve the footer of the website. Currently, the UI of the footer is not looking good. Please assign me this issue. Thank you!

![image](https://github.com/ssitvit/Code-Canvas/assets/100675296/ed0cd8f3-107d-4437-a7df-6cb1003d06f1)

**Comment by Dharmesh177** [comment]
sure assign to u !! start working and complete it in 10 days 
follow contributing.md guide for successful PR merge.
happy coding !!

**Comment by sumitkr2000** [comment]
> sure assign to u !! start working and complete it in 10 days follow contributing.md guide for successful PR merge. happy coding !!

yeah sure!
