### ISSUE TITLE
Dino Game Clone

### ISSUE THREAD

**Issue by shraddha761** [ssitvit/Code-Canvas#430]
It's clone of Dino games where a score counter is there to count Your best Score and It's responsive in nature .

Assign this issue to me under GSSOC'23

**Comment by Dharmesh177** [comment]
Have really did this much project or currently doing projects and clones in big numbers. I guess you are just doing for sack of points in gssoc. Online all projects are available we can get that as well. Too much issues and pr you have created of clones 😂😂
Like to know your point on it.
