### ISSUE TITLE
Google search engine clone

### ISSUE THREAD

**Issue by shraddha761** [ssitvit/Code-Canvas#431]
Clone of google search engine 
Assign this issue to me under GSSOC'23

**Comment by Dharmesh177** [comment]
Have really did this much project or currently doing projects and clones in big numbers. I guess you are just doing for sack of points in gssoc. Online all projects are available we can get that as well. Too much issues and pr you have created of clones 😂😂
Like to know your point on it.

**Comment by shraddha761** [comment]
> Have really did this much project or currently doing projects and clones in big numbers. I guess you are just doing for sack of points in gssoc. Online all projects are available we can get that as well. Too much issues and pr you have created of clones 😂😂 Like to know your point on it.

Everything we can find online . if I am doing for just sake of point then definitely I am on top of leaderboard 😅😂
