### ISSUE TITLE
Adding "To Top" Scroll Button and Fixing the Top

### ISSUE THREAD

**Issue by 5h0ov** [ssitvit/Code-Canvas#432]
I would like to add an arrow button to the right that, on clicking, would take the user to the top of the page.

I would also like to fix this issue that appears on the top:(Seems to be a project card)
![image](https://github.com/ssitvit/Code-Canvas/assets/83227649/5a73bdd1-94f6-4f9a-8746-b34e59452550)

It would be great to contribute to this open source project under GSSoC '23!

**Comment by marshadkhn** [comment]
Hey @5h0ov are you working with responsiveness too on this session?

**Comment by 5h0ov** [comment]
@marshadkhn  nope. Just gonna add to top button and remove that unnecessary card on the top

**Comment by marshadkhn** [comment]
Okay
