### ISSUE TITLE
Adding responsivness

### ISSUE THREAD

**Issue by marshadkhn** [ssitvit/Code-Canvas#437]
Hey @Dharmesh177, the website is really good
While I was checking the website I found a basic bug in the website

The bug is of responsiveness 
![Screenshot 2023-06-30 001030](https://github.com/ssitvit/Code-Canvas/assets/80325579/c9611f25-cccf-4e6f-8522-b7963d06acd1)
![Screenshot 2023-06-30 001050](https://github.com/ssitvit/Code-Canvas/assets/80325579/320229e1-a37e-4d68-b432-a4fb49c63aff)

Above are the some screenshot of bug
### _**Assign me this issue under GSSOC'23**_

**Comment by Dharmesh177** [comment]
Assign to u start working and complete it asap 
follow contributors.md guide for successful merge
happy coding

**Comment by palakag29** [comment]
@marshadkhn @Dharmesh177  I am already working on it. I have opened it last week. #420

**Comment by marshadkhn** [comment]
How do i reach out to you palak?

**Comment by palakag29** [comment]
??

**Comment by marshadkhn** [comment]
I want a conversation with you?
Give me your email

**Comment by palakag29** [comment]
you can say whatever you want here. no problem

**Comment by palakag29** [comment]
all cards obviously

**Comment by marshadkhn** [comment]
OK
