### ISSUE TITLE
Add some animated floating circles in the background

### ISSUE THREAD

**Issue by 5h0ov** [ssitvit/Code-Canvas#438]
I would like to add some floating particle-like circles in the background to give the website a more lively feeling!

## Example

![particles](https://github.com/ssitvit/Code-Canvas/assets/83227649/06f0a82f-5de8-4fcd-9b85-a0724b32ac47)

It would be great to contribute to this repo for GSSoC '23!

**Comment by Dharmesh177** [comment]
no need
