### ISSUE TITLE
Revamp the Portfolio Project

### ISSUE THREAD

**Issue by PoulavBhowmick03** [ssitvit/Code-Canvas#462]
Currently in the Portfolio project,the website looks very basic, the elements are overlapping and doesn't look clean. i want to make the website UI better and add some features to it
![image](https://github.com/ssitvit/Code-Canvas/assets/133862694/4c4fd066-84cc-4be5-93bd-8f620f0f817b)

**Comment by karantec** [comment]
I am from GSSoC'23.
I would like to be assigned this task.
