### ISSUE TITLE
Upgrading the UI of projects and the project box[cart] section

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [ssitvit/Code-Canvas#540]
Hello @cleveranu ,
I think Project section needs to be update because the `Search` doesn't have any search button & the font is too big for the Title section.
Also the cart text is not well maintained.

### Screenshot which I was talking about :
 
![Screenshot from 2023-08-04 22-31-33](https://github.com/ssitvit/Code-Canvas/assets/121503426/4c16ea46-f3ac-425c-abba-d357bedac497)

**Comment by Muskan1009** [comment]
@cleveranu Please assign this issue to me. I am an experienced designer would definitely make the necessary changes and make it look more promising.

**Comment by SyedImtiyaz-1** [comment]
@cleveranu Please review this.
