### ISSUE TITLE
Create a leaderboard page and add a button to it in homescreen

### ISSUE THREAD

**Issue by Shreyaar12** [ssitvit/Code-Canvas#67]
Add a leaderboard with good ui and names of all projects with images, create a column for rating as well done by Admins.

**Comment by ManasaKaza** [comment]
Hi @Shreyaar12 I would like to work on this issue under GSSoC

**Comment by Shreyaar12** [comment]
@ManasaKaza Assigning you this issue, kindly complete within 10 days

**Comment by ritik48** [comment]
hey @Shreyaar12, I would like to work on this issue.
