### ISSUE TITLE
Want to add a project on to-do list

### ISSUE THREAD

**Issue by rayarka26** [ssitvit/Code-Canvas#72]

**Comment by Shreyaar12** [comment]
Please elaborate on this and add features which makes your to do list stand out

**Comment by rayarka26** [comment]
Please assign it to me # gssoc23

**Comment by rayarka26** [comment]
I will make a to do list which will be storing new items and we can strike of any item which we feel to remove. I will be good designed.

**Comment by rayarka26** [comment]
I will make a to-do-list which will be storing new items and we can strike of any item which we feel to remove. I will be good designed. We will not be deleting the items but using material UI we will strike the items not needed. A little different from general to-do-list.

**Comment by rayarka26** [comment]
I will make a to-do-list which will be storing new items and we can strike of any item which we feel to remove. It will be good designed. We will not be deleting the items we will strike the items not needed just like a real list. A little different from general to-do-list.
