### ISSUE TITLE
[GSSoC '23] | Project Addition Weather Website

### ISSUE THREAD

**Issue by YashkShrivas4491** [ssitvit/Code-Canvas#74]
# Add a new project to the list

I'm in GSSOC'23

I want to add a new project to the list which is Weather Website link-https://yashkshrivas4491.github.io/WeatherWebApp/

This project is about building a web application to show a weather forecast using weather API from external services Open weather map.
Here you will be able to search for a specific location in the world and also it will automatically detect your current location in the beginning (for that you need to allow location) and will display all the important weather details.

# Features
Easily Fetch data from API.
Zero dependencies.
Background image changes according to the country's input.
It show humidity , wind , temperature.
if you enter wrong country's name than it show no data available.

Could you assign me this issue @cleveranu

**Comment by Dharmesh177** [comment]
assigned to u and In PR include deploy link or screenshot to assess your work. Dont forget to follow contributing.md guidelines after reviewing PR by mentor

**Comment by YashkShrivas4491** [comment]
Done ☑️
