### ISSUE TITLE
Modifying project card style [GSSoC '23]

### ISSUE THREAD

**Issue by ritik48** [ssitvit/Code-Canvas#76]
#### Problem
The project cards have category and project title on them, and some cards which have light images , on them the texts are little difficult to read.
#### Solution
I would like to add little overlay on the cards and change the position of the category and project title , so that it would look good and also be readable.

Please assign me this, so that I could work on this and make the cards more user friendly.

**Comment by Dharmesh177** [comment]
assigned to u and In PR include screenshot after changes to assess your work. Dont forget to follow contributing.md guidelines after reviewing PR by mentor

**Comment by ritik48** [comment]
thanks @Dharmesh177 , will surely abide by the contributing.md guidelines

**Comment by ritik48** [comment]
Hey @Dharmesh177 , 
This is what I came up with. If you like I can create a pr

- Before
![code canvas card mod before](https://github.com/ssitvit/Code-Canvas/assets/84488726/41eb347c-6446-4949-a331-1d80680c7c18)


- After

![code canvas card mod](https://github.com/ssitvit/Code-Canvas/assets/84488726/f70cd41c-af58-4ea7-876f-c6fcdd55e156)

**Comment by ritik48** [comment]
@Dharmesh177 Please review my pr#105
