### ISSUE TITLE
CSS Animation Project involving Two Candles

### ISSUE THREAD

**Issue by 5h0ov** [ssitvit/Code-Canvas#86]
i would like to make a project that has two candles where one candle blows out the other and it becomes dark and again gets reignited in a cute flash.

I would love to contribute to this open source project for GSSoC '23.

**Comment by Dharmesh177** [comment]
assigned to @5h0ov 
Complete this with in 1 week and 
Include screenshot or deploy link to assess your project and thereafter  include your project to main code with following the contributing.md guidelines
