### ISSUE TITLE
CSS Animation Project of File Drawers

### ISSUE THREAD

**Issue by 5h0ov** [ssitvit/Code-Canvas#87]
I would like to add a project that involves a File Drawer where each drawer can be opened and there is surprise text inside.

I would love to contribute to this open source project for GSSoC '23.

**Comment by Dharmesh177** [comment]
assigned to @5h0ov 
Complete this with in 10 days and 
Include screenshot or deploy link to assess your project and thereafter include your project to main code with following the contributing.md guidelines

**Comment by 5h0ov** [comment]
ok sir
