### ISSUE TITLE
The Simon Game

### ISSUE THREAD

**Issue by cleveranu** [ssitvit/Code-Canvas#9]
Simon is an electronic game of short-term memory skill 
**The instructions:**
1- At the start of the game, one of the four keys randomly lights up and concurrently plays a sound that corresponds to that key. The player must press the same key twice. 3- After that, the Simon randomly switches on a second light and the original one again. 4- The player must use his memory to recreate this line of lights.

**Comment by Nishannaik** [comment]
I am interested to work on this ? Can you assign it to me

**Comment by harmeetsingh11** [comment]
Hi, I am a GSSoC contributor. Can I work on this issue?

**Comment by cleveranu** [comment]
goodwork @harmeetsingh11 . I am closing this issuse.
