### ISSUE TITLE
[GSSOC 23: New Project]: Custom Music Player Software

### ISSUE THREAD

**Issue by sujanrupu** [ssitvit/Code-Canvas#99]
## **Custom Music Player (GSSOC '23)**
Custom music player application using **HTML, CSS, JavaScript**
## **Features:**

- Set Unlimited music at playlist
- Listen any music from playlist
- Make fast forward or back at any time while listening
- Randomly shuffle playlist
- Make pause and resume music at any time

**Comment by artimanputra** [comment]
assigned to @sujanrupu 
Complete this within 10 days and
Include a screenshot or deploy link to assess your project and thereafter include your project to the main code following the contributing.md guidelines.
